# -*- coding: utf-8 -*-
"""AS-BYOND-scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fsR-eyFK28nyt7mCfvo5K3HvbbM3iMB_

# 1. Install dependencies
"""

# 0. Install dependencies
import subprocess
subprocess.run(["pip", "install", "google-play-scraper"])

"""# 2. Pengumpulan Data (Scraping dengan Google Play Scraper)"""

from google_play_scraper import reviews, Sort

# 1. Pengumpulan Data (Scraping dengan Google Play Scraper)
app_id = 'co.id.bankbsi.superapp'

# Scraping reviews for BYOND by BSI app
result, _ = reviews(
    app_id,                   # App ID for BYOND by BSI
    lang='id',                # Language: Indonesian
    country='id',             # Country: Indonesia
    sort=Sort.NEWEST,         # Sort by newest reviews
    count=10000               # Minimum 10000 reviews
)

"""# Simpan Hasil Scraping (file .csv)"""

import pandas as pd

# Convert ke DataFrame
df = pd.DataFrame(result)

# Simpan hasil scraping ke CSV
df.to_csv('byond_bsi_reviews.csv', index=False)
print("Data has been saved to 'byond_bsi_reviews.csv'")